DROP USER JARAMILLO_BD CASCADE ;

CREATE USER JARAMILLO_BD IDENTIFIED BY jaramillo666;

GRANT CONNECT TO JARAMILLO_BD;
GRANT RESOURCE TO JARAMILLO_BD;

GRANT ALTER ANY INDEX TO "JARAMILLO_BD";
GRANT ALTER ANY SEQUENCE TO "JARAMILLO_BD";
GRANT ALTER ANY TABLE TO "JARAMILLO_BD";
GRANT ALTER ANY TRIGGER TO "JARAMILLO_BD";
GRANT CREATE ANY INDEX TO "JARAMILLO_BD";
GRANT CREATE ANY SEQUENCE TO "JARAMILLO_BD";
GRANT CREATE ANY SYNONYM TO "JARAMILLO_BD";
GRANT CREATE ANY TABLE TO "JARAMILLO_BD";
GRANT CREATE ANY TRIGGER TO "JARAMILLO_BD";
GRANT CREATE ANY VIEW TO "JARAMILLO_BD";
GRANT CREATE PROCEDURE TO "JARAMILLO_BD";
GRANT CREATE PUBLIC SYNONYM TO "JARAMILLO_BD";
GRANT CREATE TRIGGER TO "JARAMILLO_BD";
GRANT CREATE VIEW TO "JARAMILLO_BD";
GRANT DELETE ANY TABLE TO "JARAMILLO_BD";
GRANT DROP ANY INDEX TO "JARAMILLO_BD";
GRANT DROP ANY SEQUENCE TO "JARAMILLO_BD";
GRANT DROP ANY TABLE TO "JARAMILLO_BD";
GRANT DROP ANY TRIGGER TO "JARAMILLO_BD";
GRANT DROP ANY VIEW TO "JARAMILLO_BD";
GRANT INSERT ANY TABLE TO "JARAMILLO_BD";
GRANT QUERY REWRITE TO "JARAMILLO_BD";
GRANT SELECT ANY TABLE TO "JARAMILLO_BD";
GRANT UNLIMITED TABLESPACE TO "JARAMILLO_BD";

